services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: configs
      POSTGRES_USER: configs
      POSTGRES_PASSWORD: configs
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      APP_PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: configs
      DB_USER: configs
      DB_PASSWORD: configs
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  pgdata: {}
